# application.yml for git backend

server:
    port: 8888
    servlet:
        context-path: /config-server

spring:
    profiles:
        active: local
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/nihalmurmu/config-repo
                    basedir: target/config